### ISSUE TITLE
How can I disable the alert output

### ISSUE THREAD

**Issue by FokkeZB** [hackscribble/hackscribble-MCP9804-library#1]
After using `configureAlert()` to activate the alert output, how can I disable this again?

**Comment by hackscribble** [comment]
Hi.  That's not supported by the library at present.  I will investigate and see if I can release a version that adds it.  Thanks.

**Comment by hackscribble** [comment]
I've posted my backlog tasks as issues in this repository.  Disabling the alert output would ideally be implemented as part of #5. If you urgently need this feature, I will produce an interim release that adds a method for it.  Otherwise, it will be included in the next main release.

**Comment by FokkeZB** [comment]
For now I just detach the interrupt change listener and put the sensor in sleep so it's not that much of a problem but good to see you have lots of stuff ligned up!

**Comment by hackscribble** [comment]
OK, I'll include it in version 1.0.  Thanks.

**Comment by hackscribble** [comment]
Hi FokkeZB.  

I'm working on the design of the new alert configuration methods.  I would appreciate your opinion on these options for disabling the alert ...

Option 1 is to enhance the existing `configureAlert()` method. So `configureAlert(ENABLE)` would do the same as the current `configureAlert()` and `configureAlert(DISABLE)` would disable it.

Option 2 is to introduce new methods `enableAlert()` and  `disableAlert()`. I would retain but deprecate `configureAlert()` for backwards compatibility.

For setting the alert options when enabling the alert, I'm thinking of adding an additional parameter to either `configureAlert()` or `enableAlert()` with symbolic constants that get ORed to give the settings required.  For example ...

`configureAlert(ENABLE, ALERT_TCRIT | ALERT_ACTIVE_HIGH | ALERT_COMPARATOR)`
`configureAlert(ENABLE, ALERT_ALL | ALERT_ACTIVE_LOW | ALERT_INTERRUPT)`

An alternative would be individual set functions, for example `setAlertType(ALL)`, `setAlertPolarity(HIGH)`, etc.

Thanks

**Comment by FokkeZB** [comment]
I'd re-use `configureAlert()` and default it to `true` and `ALERT_ALL`.

**Comment by hackscribble** [comment]
I've pushed a new branch to the repo called `test-0.2`.  

In this version, `configureAlert()` without arguments does the same as in version 0.1 beta.  You can also call it as `configureAlert(ENABLE)'`.  To disable the alert, call `configureAlert(DISABLE)`.

You can also set the alert parameters like this:

`configureAlert(ENABLE, ALERT_ALL | ALERT_HIGH | ALERT_COMPARATOR`.  The options for the arguments are listed in the .h file.

If you like, please download the new .cpp and .h and give it at test.  If it works OK, I will publish it as a proper 0.2 release with updated documentation.

**Comment by FokkeZB** [comment]
It seems to work fine, thx!

**Comment by hackscribble** [comment]
Thanks for testing it.  I will tidy up the documentation this week and release it formally as version 0.2.
